<?xml version="1.0"?>
<package format="3">
  <name>cpr_orchard_gazebo</name>
  <version>0.2.8</version>
  <description>The cpr_orchard_gazebo package</description>

  <maintainer email="civerachb@clearpathrobotics.com">Chris Iverach-Brereton</maintainer>
  <author email="dniewinski@clearpathrobotics.com">Dave Niewinski</author>

  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>cpr_accessories_gazebo</exec_depend>
  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>agilex_scout</exec_depend>
  <exec_depend>husky_gazebo</exec_depend>
  <exec_depend>jackal_gazebo</exec_depend>
  <exec_depend>warthog_gazebo</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
