<?xml version="1.0"?>
<package format="3">
  <name>cpr_obstacle_gazebo</name>
  <version>0.2.8</version>
  <description>The cpr_obstacle_gazebo package</description>

  <maintainer email="jmastrangelo@clearpathrobotics.com">Jose Mastrangelo</maintainer>
  <author email="jmastrangelo@clearpathrobotics.com">Jose Mastrangelo</author>
  <author email="civerachb@clearpathrobotics.com">Chris Iverach-Brereton</author>

  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>gazebo_plugins</exec_depend>
  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>hector_gazebo_plugins</exec_depend>
  <exec_depend>pointcloud_to_laserscan</exec_depend>

  <exec_depend>scout_description</exec_depend>
  <exec_depend>boxer_gazebo</exec_depend>
  <exec_depend>dingo_gazebo</exec_depend>
  <exec_depend>husky_gazebo</exec_depend>
  <exec_depend>jackal_gazebo</exec_depend>
  <exec_depend>warthog_gazebo</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
